//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ferienedteller3null.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Ferienedteller3null.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julen ringes inn om.
        /// </summary>
        internal static string Chrismas_ChristmasRingin {
            get {
                return ResourceManager.GetString("Chrismas_ChristmasRingin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God jul.
        /// </summary>
        internal static string Christmas_MerryChristmas {
            get {
                return ResourceManager.GetString("Christmas_MerryChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juleferie om.
        /// </summary>
        internal static string Christmas_Vacation {
            get {
                return ResourceManager.GetString("Christmas_Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Lofoten {
            get {
                object obj = ResourceManager.GetObject("Lofoten", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon nedtelling_ikon {
            get {
                object obj = ResourceManager.GetObject("nedtelling_ikon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SnowyChristmas {
            get {
                object obj = ResourceManager.GetObject("SnowyChristmas", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May the force be with you.
        /// </summary>
        internal static string StarWars_mayTheForceBeWithYou {
            get {
                return ResourceManager.GetString("StarWars_mayTheForceBeWithYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dager til min forestilling av Star Wars.
        /// </summary>
        internal static string StarWars_MyDate {
            get {
                return ResourceManager.GetString("StarWars_MyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dager til premieren av Star Wars.
        /// </summary>
        internal static string StarWars_Premiere {
            get {
                return ResourceManager.GetString("StarWars_Premiere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap StarWarsChrismas {
            get {
                object obj = ResourceManager.GetObject("StarWarsChrismas", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap StarWarsDarkside {
            get {
                object obj = ResourceManager.GetObject("StarWarsDarkside", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
