//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Ferienedteller3null.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2015-12-23")]
        public DateTime SelectedVacationData {
            get {
                return ((DateTime)(this["SelectedVacationData"]));
            }
            set {
                this["SelectedVacationData"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Hei, Julenisse!")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Red")]
        public Color FontColor {
            get {
                return ((Color)(this["FontColor"]));
            }
            set {
                this["FontColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Standard")]
        public string SelectedTheme {
            get {
                return ((string)(this["SelectedTheme"]));
            }
            set {
                this["SelectedTheme"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool UseShortStrings {
            get {
                return ((bool)(this["UseShortStrings"]));
            }
            set {
                this["UseShortStrings"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AllwaysOnTop {
            get {
                return ((bool)(this["AllwaysOnTop"]));
            }
            set {
                this["AllwaysOnTop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool StarWarsCountDown {
            get {
                return ((bool)(this["StarWarsCountDown"]));
            }
            set {
                this["StarWarsCountDown"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2015-12-16")]
        public DateTime StarWarsMyDate {
            get {
                return ((DateTime)(this["StarWarsMyDate"]));
            }
            set {
                this["StarWarsMyDate"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2015-12-16")]
        public DateTime StarWarsPremierDate {
            get {
                return ((DateTime)(this["StarWarsPremierDate"]));
            }
            set {
                this["StarWarsPremierDate"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public DateTime StarWarsMyHour {
            get {
                return ((DateTime)(this["StarWarsMyHour"]));
            }
            set {
                this["StarWarsMyHour"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public DateTime selectedVacationHour {
            get {
                return ((DateTime)(this["selectedVacationHour"]));
            }
            set {
                this["selectedVacationHour"] = value;
            }
        }
    }
}
